CREATE USER SPRING IDENTIFIED BY SPRING;

GRANT CONNECT, RESOURCE, DBA TO SPRING;

/*
작성자 : 육심규
편집일 : 2022-07-05
프로젝트명 : 쇼핑몰DEMO
*/

/* 테이블 생성 */
--1. 회원가입 테이블
CREATE TABLE TBL_MEMBER(
	MEM_ID					VARCHAR2(15)					    CONSTRAINT PK_MEM_ID PRIMARY KEY,
	MEM_NAME             	VARCHAR2(30)						NOT NULL,
	MEM_PW                 	CHAR(60)    						NOT NULL,
	MEM_ZIPCODE         	CHAR(5) 							NOT NULL,
	MEM_ADDR              	VARCHAR2(100)						NOT NULL,
	MEM_ADDR_D			    VARCHAR2(100)						NOT NULL,
	MEM_PHONE          	    VARCHAR2(15)						NOT NULL,
	MEM_NICK             	VARCHAR2(20)						NOT NULL UNIQUE,
    MEM_EMAIL            	VARCHAR2(50)						NOT NULL UNIQUE,
	MEM_ACCEPT_E      	    CHAR(1)         DEFAULT 'Y'			NOT NULL,
	MEM_POINT				NUMBER          DEFAULT 0          	NOT NULL,
	MEM_DATE_SUB      	    DATE            DEFAULT SYSDATE   	NOT NULL,
	MEM_DATE_UP        	    DATE            DEFAULT SYSDATE		NOT NULL,
	MEM_DATE_LAST   	    DATE            DEFAULT SYSDATE    	NOT NULL,
	MEM_AUTHCODE		    CHAR(1)         DEFAULT 'N'
	-- MEM_SESSION_KEY	        VARCHAR2(50),
	-- MEM_SESSION_LIMIT	    TIMESTAMP
);

--2. 카테고리 테이블
CREATE TABLE TBL_CATEGORY (
    CG_CODE_C       			NUMBER        				PRIMARY KEY,
    CG_CODE_P     		        NUMBER,                                          
    CG_NAME           		    VARCHAR2(50)         		NOT NULL
);

INSERT INTO TBL_CATEGORY VALUES(1, NULL, 'TOP');

INSERT INTO TBL_CATEGORY VALUES(1001, 1, '반팔티');
INSERT INTO TBL_CATEGORY VALUES(1002, 1, '나시');
INSERT INTO TBL_CATEGORY VALUES(1003, 1, '프린팅티');
INSERT INTO TBL_CATEGORY VALUES(1004, 1, '니트');
INSERT INTO TBL_CATEGORY VALUES(1005, 1, '맨투맨');
INSERT INTO TBL_CATEGORY VALUES(1006, 1, '긴팔티');

INSERT INTO TBL_CATEGORY VALUES(2, NULL, 'SHIRTS');

INSERT INTO TBL_CATEGORY VALUES(2001, 2, '베이직');
INSERT INTO TBL_CATEGORY VALUES(2002, 2, '청남방');
INSERT INTO TBL_CATEGORY VALUES(2003, 2, '체크');
INSERT INTO TBL_CATEGORY VALUES(2004, 2, '스트라이프');
INSERT INTO TBL_CATEGORY VALUES(2005, 2, '헨리넥');

INSERT INTO TBL_CATEGORY VALUES(3, NULL, 'PANTS');

INSERT INTO TBL_CATEGORY VALUES(3001, 3, '슬랙스');
INSERT INTO TBL_CATEGORY VALUES(3002, 3, '면바지');
INSERT INTO TBL_CATEGORY VALUES(3003, 3, '청바지');
INSERT INTO TBL_CATEGORY VALUES(3004, 3, '밴딩팬츠');
INSERT INTO TBL_CATEGORY VALUES(3005, 3, '반바지');

COMMIT;

--3. 상품 테이블
CREATE TABLE TBL_PRODUCT(
    PDT_NUM					NUMBER								CONSTRAINT PK_PDT_NUM PRIMARY KEY,
    CG_NUM_2                NUMBER,
    CG_NUM_1                NUMBER,
    PDT_NAME				VARCHAR2(50)						NOT NULL,
    PDT_PRICE				NUMBER								NOT NULL,
    PDT_DISCOUNT			NUMBER								NOT NULL,
    PDT_COMPANY			    VARCHAR2(30)						NOT NULL,
    PDT_DETAIL				VARCHAR2(4000)					    NOT NULL,
    PDT_IMG					VARCHAR2(200)						NOT NULL,
    PDT_IMG_FOLDER          VARCHAR2(50)						NOT NULL,
    PDT_AMOUNT			    NUMBER								NOT NULL,
    PDT_BUY					CHAR(1) DEFAULT 'Y'					NOT NULL,
    PDT_DATE_SUB			DATE 		DEFAULT SYSDATE			NOT NULL,
    PDT_DATE_UP			    DATE        DEFAULT SYSDATE			NOT NULL
);
DROP TABLE TBL_PRODUCT;
-- 상품코드 시퀀스
CREATE SEQUENCE SEQ_TBL_PRODUCT_NUM;

INSERT INTO TBL_PRODUCT
					( PDT_NUM, CG_NUM_2, CG_NUM_1, PDT_NAME, PDT_PRICE,
					  PDT_DISCOUNT, PDT_COMPANY, PDT_DETAIL, PDT_IMG, PDT_IMG_FOLDER, PDT_AMOUNT, PDT_BUY )
		VALUES
					( SEQ_TBL_PRODUCT_NUM.NEXTVAL, 1, 2, '1', 1, 1, '1', '1', '1', '1', 1, 'Y');

--4. 장바구니 테이블 
CREATE TABLE TBL_CART(
	CART_CODE				NUMBER								PRIMARY KEY,			
	PDT_NUM				    NUMBER								NOT NULL,
	MEM_ID					VARCHAR2(20)						NOT NULL,
	CART_AMOUNT			    NUMBER								NOT NULL,
    FOREIGN KEY(PDT_NUM) REFERENCES TBL_PRODUCT(PDT_NUM),
    FOREIGN KEY(MEM_ID) REFERENCES TBL_MEMBER(MEM_ID)
);

--5. 주문 테이블
CREATE TABLE TBL_ORDER(
	ODR_CODE				NUMBER								CONSTRAINT PK_ODR_CODE PRIMARY KEY,
	MEM_ID					VARCHAR2(60)						NOT NULL,
	ODR_NAME				VARCHAR2(30)						NOT NULL,
	ODR_ZIPCODE			    CHAR(5)								NOT NULL,
	ODR_ADDR				VARCHAR2(50)						NOT NULL,
	ODR_ADDR_D			    VARCHAR2(50)						NOT NULL,
	ODR_PHONE				VARCHAR2(20)						NOT NULL,
	ODR_TOTAL_PRICE		    NUMBER								NOT NULL,
	ODR_DATE				DATE        DEFAULT SYSDATE			NOT NULL,
    FOREIGN KEY(MEM_ID) REFERENCES TBL_MEMBER(MEM_ID)
);

--6. 주문 상세 테이블
CREATE TABLE TBL_ORDER_DETAIL(
	ODR_CODE				NUMBER							NOT NULL,
	PDT_NUM				    NUMBER							NOT NULL,
	ODR_AMOUNT			    NUMBER							NOT NULL,
	ODR_PRICE				NUMBER							NOT NULL,
	PRIMARY KEY (ODR_CODE, PDT_NUM),
    FOREIGN KEY(ODR_CODE) REFERENCES TBL_ORDER(ODR_CODE),
    FOREIGN KEY(PDT_NUM) REFERENCES TBL_PRODUCT(PDT_NUM)
);

--7. 게시판 테이블
CREATE TABLE TBL_BOARD(
	BRD_NUM				    NUMBER							CONSTRAINT PK_BRD_NUM PRIMARY KEY,
	MEM_ID					VARCHAR2(15)					NOT NULL,
	BRD_TITLE				VARCHAR2(100)					NOT NULL,
	BRD_CONTENT			    VARCHAR2(4000)					NOT NULL,
	BRD_DATE_REG			DATE        DEFAULT SYSDATE		NOT NULL,
    FOREIGN KEY(MEM_ID) REFERENCES TBL_MEMBER(MEM_ID)
);

--8. 상품후기 테이블 
CREATE TABLE TBL_REVIEW(
	RV_NUM					NUMBER								CONSTRAINT PK_RV_NUM PRIMARY KEY,
	MEM_ID					VARCHAR2(50)						NOT NULL,
	PDT_NUM				    NUMBER								NOT NULL,
	RV_CONTENT			    VARCHAR2(200)						NOT NULL,
	RV_SCORE				NUMBER								NOT NULL,
	RV_DATE_REG			    DATE        DEFAULT SYSDATE			NOT NULL,
    FOREIGN KEY(MEM_ID) REFERENCES TBL_MEMBER(MEM_ID),
    FOREIGN KEY(PDT_NUM) REFERENCES TBL_PRODUCT(PDT_NUM)
);

--9. 관리자 로그인 테이블
CREATE TABLE TBL_ADMIN(
	ADMIN_ID				VARCHAR2(15)						PRIMARY KEY,
	ADMIN_PW				CHAR(60)    						NOT NULL,
	ADMIN_NAME			    VARCHAR2(15)						NOT NULL,
	ADMIN_DATE_LATE	        DATE        		                NOT NULL
);


/* 테이블 조회 */
SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_CATEGORY;
SELECT * FROM TBL_PRODUCT;
SELECT * FROM TBL_CART;
SELECT * FROM TBL_ORDER;
SELECT * FROM TBL_ORDER_DETAIL;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_REVIEW;




select mem_id from tbl_member where mem_id = dbrtlarb;

SELECT MEM_ID
FROM TBL_MEMBER
WHERE MEM_ID = 'dbrtlarb';




insert into TBL_ADMIN
values('admin', '$2a$10$rfHhMGtD4b.ar9AppvkbNON6vIcpmJPKtpD8WHh7TzL5jfXDlN/fe', '관리자', sysdate);

commit;

SELECT ADMIN_ID, ADMIN_PW, ADMIN_NAME, ADMIN_DATE_LATE
FROM TBL_ADMIN;


INSERT INTO PDT_NUM, CG_NUM_1, CG_NUM_2, PDT_NAME, PDT_PRICE,
PDT_DISCOUNT, PDT_COMPANY, PDT_DETAIL, PDT_IMG, PDT_IMG_FOLDER,
PDT_AMOUNT, PDT_BUY, PDT_DATE_SUB, PDT_DATE_UP
VALUES();

CREATE SEQUENCE SEQ_TBL_PRODUCT_NUM;


